[{
	"regexp": "^!tips$",
	"response": "http:\/\/thephish.fm\/tips\/"
}, {
	"regexp": "^!(about|commands)$",
	"response": "https:\/\/github.com\/ehedaya\/theSloth\/wiki\/Commands"
}, {
	"regexp": "^!(sloth)$",
	"response": "http:\/\/bit.ly\/theSlothExt"
}, {
	"regexp": "^!(bugs|bug|feature|features)$",
	"response": "https:\/\/github.com\/ehedaya\/theSloth\/issues\/new\/"
}, {
	"regexp": "^!stats$",
	"response": "http:\/\/stats.thephish.fm"
}, {
	"regexp": "^!gifs$",
	"response": "http:\/\/tinyurl.com\/ttgifs"
}, {
	"regexp": "^!deg$",
	"response": "http:\/\/tinyurl.com\/phishdeg"
}, {
	"regexp": "^!m[e]{1,2}[t]{1,2}up[s]{0,1}$",
	"response": "http:\/\/thephish.fm\/meettups"
}, {
	"regexp": "^!attendance$",
	"response": "http:\/\/thephish.fm\/attendance"
}, {
	"regexp": "^!tickets$",
	"response": "http:\/\/thephish.fm\/tickets"
}, {
	"regexp": "^!tease$",
	"response": "http:\/\/thephish.fm\/tease"
}, {
	"regexp": "^!draft$",
	"response": "http:\/\/thephish.fm\/draft"
}, {
	"regexp": "^!(ss|secretsanta|secrettsantta|secrettsanta|secretsantta)$",
	"response": "http:\/\/thephish.fm\/secrettstantta"
}, {
	"regexp": "^!replayroom$",
	"response": "http:\/\/thephish.fm\/replayroom"
}, {
	"regexp": "^!pnet$",
	"response": "Enter all the shows you attended into Phish.net, then type !pnet:your_phishnet_username into the chat to be included in !who lists."
}, {
	"regexp": "^!whatever$",
	"response": "\u00af\\_(\u30c4)_\/\u00af"
}, {
	"regexp": "^!ext",
	"response": "http:\/\/thephish.fm\/tips#extensions"
}, {
	"regexp": "^!g?chat$",
	"response": "http:\/\/thephish.fm\/gchat"
}, {
	"regexp": "^!getreplay$",
	"response": "http:\/\/thephish.fm\/how-to-dj-a-replay"
}, {
	"regexp": "^!schedule$",
	"response": "http:\/\/thephish.fm\/schedule"
}, {
	"regexp": "^!request$",
	"response": "http:\/\/thephish.fm\/requestform"
}, {
	"regexp": "^!facebook$",
	"response": "https:\/\/www.facebook.com\/groups\/thephish\/"
}, {
	"regexp": "^!twitter$",
	"response": "https:\/\/twitter.com\/thephishfromtt"
}, {
	"regexp": "^!blog$",
	"response": "http:\/\/thephish.fm\/"
}, {
	"regexp": "^!dates$",
	"response": "http:\/\/thephish.fm\/dates"
}, {
	"regexp": "^!adding$",
	"response": "http:\/\/thephish.fm\/tips#adding"
}, {
	"regexp": "^!nola$",
	"response": "http:\/\/thephish.fm\/nola"
}, {
	"regexp": "^!lyrics$",
	"response": "http:\/\/thephish.fm\/lyrics"
}, {
	"regexp": "^!psotw$",
	"response": "http:\/\/thephish.fm\/psotw"
}, {
	"regexp": "^!jazzfest$",
	"response": "http:\/\/thephish.fm\/jazzfest"
}, {
	"regexp": "^!dash(board)?$",
	"response": "http:\/\/thephish.fm\/dashboard"
}, {
	"regexp": "^!best(of)?$",
	"response": "http:\/\/thephish.fm\/best-of"
}, {
	"regexp": "^!translate$",
	"response": "https:\/\/translate.google.com\/"
}, {
	"regexp": "^!squares",
	"response": "http:\/\/thephish.fm\/squares"
}, {
	"regexp": "^!bracket$",
	"response": "http:\/\/thephish.fm\/bracket"
}, {
	"regexp": "^!welcome",
	"response": "Welcome to thePhish. We only play music by the band Phish in here unless otherwise specified. If you do not play Phish (or music containing a member of Phish) you will be skipped."
}, {
	"regexp": "^!pland$",
	"response": "http:\/\/thephish.fm\/plan-d"
}, {
	"regexp": "^!soundcloud$",
	"response": "http:\/\/thephish.fm\/soundcloud"
}, {
	"regexp": "^!rv$",
	"response": "http:\/\/thephish.fm\/rv"
}, {
	"regexp": "^!mexico",
	"response": "http:\/\/thephish.fm\/mexico"
}, {
	"regexp": "^!stream",
	"response": "http:\/\/thephish.fm\/stream"
}, {
	"regexp": "^!hold$",
	"response": "https:\/\/i.imgur.com\/7sMLc6V.png"
}, {
	"regexp": "^!mcm$",
	"response": "https:\/\/www.youtube.com\/watch?v=FCJFmL4oxPE"
}, {
	"regexp": "^!tourann",
	"response": "http:\/\/thephish.fm\/tour-announcements"
}]
